services:
  flask_api:
    build: .
    container_name: flask_api
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db #Was localhost
    networks:
      - flask_network
  
  db: #Was localhost
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local